name: 'todoTest'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: 2.0.0-beta.1
  browser: '>=0.10.0 <0.11.0'
  csso_transformer: any
  dart_to_js_script_rewriter: '^0.1.0'
  http: "^0.11.3+3"

transformers:
- dart_to_js_script_rewriter
- angular2:
    entry_points: web/main.dart
- csso_transformer
